sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.5
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 5.6
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: hhvm
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
  fast_finish: true

before_script:
  - composer self-update
  - composer update $COMPOSER_FLAGS --prefer-source

script:
  - ./vendor/bin/parallel-lint src tests
  - ./vendor/bin/phpunit --verbose
  - ./vendor/bin/phpcs src --standard=psr2 -sp

after_script: php vendor/bin/coveralls
