language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

addons:
  apt:
    packages:
      - uuid-dev

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then printf "\n" | pecl install uuid; fi;'
  - phpenv rehash

script:
  - mkdir -p build/logs
  - ./vendor/bin/parallel-lint src tests
  - ./vendor/bin/phpunit --verbose
  - ./vendor/bin/phpcs src --standard=psr2 -sp

after_script:
  - php vendor/bin/coveralls

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/f3356db3405001e47b5e'
    on_success: change
    on_failure: always
    on_start: false
